global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'lingulu-ml-monitor'

scrape_configs:
  - job_name: 'lingulu-ml-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
    scrape_interval: 5s
    scrape_timeout: 5s
